export enum RoutesEnum {
    NOT_FOUND = '*',
    HOME = '/',
    POSTS = '/posts',
    POST = '/post/:postId',
    MY_PROFILE = '/my-profile',
    LOGIN = '/login',
    REQUEST_PASSWORD_RESET = '/reset-password',
    RESET_PASSWORD = '/reset-password/:hash',
    CATEGORIES = '/categories',
    SALE = '/sale',
    CONTACT_US = '/contact-us',
    TEAMS = '/teams',
    PRIVACY = '/privacy',
    SECURITY = '/security',
    REGISTRATION = '/registration',
}
